# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 13:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posts',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 8, 2, 13, 34, 15, 549073, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
