# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_read_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='read_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
