# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models.posts


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20170731_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=posts.models.posts.upload_location, width_field='width_field'),
        ),
    ]
